### PR TITLE
sensors: fix HT_NXT_SUPER_PRO_SENSOR command list

### PR DESCRIPTION
**Pull request by keenanjohnson**
HT_NXT_SUPER_PRO_SENSOR only enumerated 5 out of it's 8 supported commands.

### CODE REVIEW

**Comment by keenanjohnson** [comment]
I'm not sure if there is anything else I need to update or if this five was put here intentionally, but it seems wrong to me.

[See the docs here for the list of all the commands as a double check.](http://docs.ev3dev.org/projects/lego-linux-drivers/en/ev3dev-stretch/sensor_data.html#hitechnic-nxt-superpro-prototype-board)

image

**Comment by dlech** [comment]
Thanks!

For the record, we also noticed that there are some issues with the data conversion - e.g. AIN is not 16-bit little-endian, but rather the first byte is the 8 highest bits and the second byte is the two lowest bits. So there is more work to be done on this sensor to make it work properly.

**Comment by keenanjohnson** [comment]
Yes! Are there issues for this project? Should I open one so we don't forget?

**Comment by dlech** [comment]
https://github.com/ev3dev/ev3dev/issues

**Pull request merged**
