### PR TITLE
fixed NxtServo and NxtMMX doc

### PR DESCRIPTION
**Pull request by in4lio**

### CODE REVIEW

**Comment by dlech** [comment]
Thanks!

**Comment by in4lio** [comment]
Not at all) Will EV3SensorMUX and NSX2020 (NXT Sensor Multiplexer) port names have i2c address field like NxtNMX?

**Comment by dlech** [comment]
The EV3SensorMUX and NSX2020 *should* include the i2c address in the port name. If they don't, it is a bug and you should open an issue for it.

**Comment by in4lio** [comment]
I have no these two)
```
int ms_nxtmmx_probe_cb(struct nxt_i2c_sensor_data *data)
{
	...
	snprintf(smux->port.port_name, LEGO_PORT_NAME_SIZE, "%s:mux%d",
		 data->port_name, ret);
```
Is the address in `data->port_name`?

**Comment by dlech** [comment]
I just tested them and both have the `:i2c<Y>:` in the port name, so yes, `data->port_name` must already include the address.

**Comment by in4lio** [comment]
Thanks!

**Pull request merged**
