### PR TITLE
changing HiTechnic IrSeeker V2 docs based on #1525

### PR DESCRIPTION
**Pull request by Eisverygoodletter**
changing some comments based off https://github.com/ev3dev/ev3dev/issues/1525

### CODE REVIEW

**Comment by dlech** [comment]
Did you actually see values of 130? Or is it possible that the max is 127? The latter would make sense if they are using a signed 8-bit value.

**Comment by Eisverygoodletter** [comment]
I actually measured a value of 170 when I put the IR ball really close to the sensor and orient the IR ball so that the light sources point directly at the sensor. https://www.robotshop.com/media/files/pdf/introduction-nsk1042.pdf says that it should be a byte (8 bits), so I think they may be using an unsigned 8-bit value.

**Comment by dlech** [comment]
> so I think they may be using an unsigned 8-bit value.

I think so too, so lets make the range 0-255.

**Comment by Eisverygoodletter** [comment]
Ok, but should I leave a note like "80 signal strength is approximately N cm distance "?

**Comment by dlech** [comment]
I'm not sure how much that depends on the environment, especially with DC mode.

If you are quite sure that is accurate and most people will get the same results, we can add a footnote for it.

**Comment by Eisverygoodletter** [comment]
Maybe let's add a footnote saying that values may not reach as high as 255 and is dependent on IR source strength and many other factors

**Comment by dlech** [comment]
Sounds good.

**Comment by Eisverygoodletter** [comment]
Here's a temporary build of the docs that show how the docs look like after the changes. https://irseeker-temporary-lego-linux-drivers.readthedocs.io/en/latest/sensor_data.html#hitechnic-nxt-irseeker-v2 Do you think that I should split the text into more footnotes, or should I keep it clean in 1 or 2 footnotes?

**Comment by dlech** [comment]
I think it is fine the way it is.

**Comment by Eisverygoodletter** [comment]
Then I think that that's pretty much all the changes done, ready to merge

**Comment by dlech** [comment]
Thanks!

**Pull request merged**
