### PR TITLE
Fix race condition in setting tm->command

### PR DESCRIPTION
**Pull request by rhempel**
- Addresses ev3dev/ev3dev#661
- Addresses ev3dev/ev3dev#687

### CODE REVIEW

**Comment by dlech** [comment]
The reason `tm->command = cmd;` is where it is is because it would result in an incorrect value if `tm_send_command` failed. i.e. if `tacho_motor_class_start_motor_ramp` returns an error, now `tm->command` is incorrect.

There were a number of other places where we faced similar race conditions with `tm->active_params`. The way I fixed it was by passing `new_params` to `tacho_motor_class_start_motor_ramp` so that it had the new value.

I'm not saying this is the right or best way to do it, but it seemed like the best solution to me when I was fixing the other race conditions.

**Comment by dlech** [comment]
Here is the relevant commit to what I was talking about with `new_params`: https://github.com/ev3dev/lego-linux-drivers/commit/2644e9f90b3cb96c60805d10850222cbf2d2b340

**Comment by rhempel** [comment]
I understand about command being potentially incorrect, but the problem is that we need at least one full ramp delay or else the value of `tm->command` is from the previous motion. That's why we get a very brief period (the first ramp period) where the motor runs in the wrong direction. Either way, this fixes the defect, so is the code acceptable or is there a better way around the problem, perhaps passing the command to `tacho_motor_class_start_motor_ramp()`?

**Comment by dlech** [comment]
I would be afraid that this change as it is would introduce other subtle bugs if motors are not behaving properly. I would rather see it passed as a parameter like `new_params`.

Or perhaps we could even make `tm->command` a field of `struct tacho_motor_params` instead of having it as a separate variable.

Or you could just set `tm->command` back to it's previous value if there is an error.

**Comment by rhempel** [comment]
OK, I'll most likely update the code by making `tm->command` a field of `struct tacho_motor_params` - stay tuned.

**Comment by rhempel** [comment]
Grr - I'll squash the commits before the actual merge. Code is tested and seems to work pretty well. I have only built this for the EV3, so I'm not sure if there are merge issues with other platforms..

**Comment by dlech** [comment]
I like the feel of having `tm->command` in parameters. I think it is an improvement beyond just fixing the bug.

And you can now squash commits via the GitHub web interface (as long as you want it to be a single commit).

**Pull request merged**
